### ISSUE TITLE
[PSST] Record WARNING status code

### ISSUE THREAD

**Issue by bbockelm** [CMSCompOps/MonitoringScripts#91]
In MONIT, we cannot do graphs based on the WARNING code, making it difficult to determine the common causes of warnings without looking at logs.

Can we add this status code field?

@roksys

**Comment by roksys** [comment]
Recording of WARNING codes [10040;10050] were added.
https://monit-kibana.cern.ch/goto/b7c5dd5a54898929cf0a2fee2587c18b
